language: node_js
sudo: false
node_js: 8.4.0
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: npm install
jobs:
  include:
    - stage: unit and integration test
      script: npm test
    - stage: functional test
      before_script: npm start & sleep 7
      script: npm run test:functional
